////------------------------------------------------------------------------------
//// <auto-generated>
////    This code was generated from a template.
////
////    Manual changes to this file may cause unexpected behavior in your application.
////    Manual changes to this file will be overwritten if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace MvcMusicStore.Models
//{
//    using System;
//    using System.Collections.Generic;
    
//    public partial class Album
//    {
//        public Album()
//        {
//            this.Carts = new HashSet<Cart>();
//            this.OrderDetails = new HashSet<OrderDetail>();
//        }
    
//        public int AlbumId { get; set; }
//        public int GenreId { get; set; }
//        public int ArtistId { get; set; }
//        public string Title { get; set; }
//        public decimal Price { get; set; }
//        public string AlbumArtUrl { get; set; }
    
//        public virtual Artist Artist { get; set; }
//        public virtual Genre Genre { get; set; }
//        public virtual ICollection<Cart> Carts { get; set; }
//        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
//    }
//}

////------------------------------------------------------------------------------
//// <auto-generated>
////    This code was generated from a template.
////
////    Manual changes to this file may cause unexpected behavior in your application.
////    Manual changes to this file will be overwritten if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace MvcMusicStore.Models
//{
//    using System;
//    using System.Collections.Generic;

//    public partial class Album
//    {
//        public Album()
//        {
//            this.Carts = new HashSet<Cart>();
//            this.OrderDetails = new HashSet<OrderDetail>();
//        }

//        public int AlbumId { get; set; }
//        public int GenreId { get; set; }
//        public int ArtistId { get; set; }
//        public string Title { get; set; }
//        public decimal Price { get; set; }
//        public string AlbumArtUrl { get; set; }

//        public virtual Artist Artist { get; set; }
//        public virtual Genre Genre { get; set; }
//        public virtual ICollection<Cart> Carts { get; set; }
//        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
//    }
//}

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace MvcMusicStore.Models
{
    [MetadataType(typeof(AlbumMetaData))]
    public partial class Album
    {
        public Album()
        {
            this.Carts = new HashSet<Cart>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }

        public int AlbumId { get; set; }
        public int GenreId { get; set; }
        public int ArtistId { get; set; }
        public string Title { get; set; }
        public decimal Price { get; set; }
        public string AlbumArtUrl { get; set; }

        public virtual Artist Artist { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        // Validation rules for the Album class

        [Bind(Exclude = "AlbumId")]
        public class AlbumMetaData
        {
            [ScaffoldColumn(false)]
            public object AlbumId { get; set; }

            [DisplayName("Genre")]
            public object GenreId { get; set; }

            [DisplayName("Artist")]
            public object ArtistId { get; set; }

            [Required(ErrorMessage = "An Album Title is required")]
            [DisplayFormat(ConvertEmptyStringToNull = false)]
            [StringLength(160)]
            public object Title { get; set; }

            [DisplayName("Album Art URL")]
            [StringLength(1024)]
            public object AlbumArtUrl { get; set; }

            [Required(ErrorMessage = "Price is required")]
            [Range(0.01, 100.00, ErrorMessage = "Price must be between 0.01 and 100.00")]
            public object Price { get; set; }
        }
    }
}
